name: socialmediathingnametbd

services:
  socialmediathingnametbd-api:
    build:
      context: ../
      dockerfile: docker/socialmediathingnametbd-api/Dockerfile
      target: final
    network_mode: host
    env_file:
      - socialmediathingnametbd-api/.env
    depends_on:
      postgres:
        condition: service_healthy
  
  postgres:
    image: postgres:18
    restart: unless-stopped
    environment:
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/18/data
    secrets:
      - postgres_db
      - postgres_user
      - postgres_password
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d \"$(cat /run/secrets/postgres_db)\" -U \"$(cat /run/secrets/postgres_user)\"" ]
      interval: 10s
      timeout: 5s
      retries: 5

secrets:
  postgres_db:
    file: secrets/POSTGRES_DB.txt
  postgres_user:
    file: secrets/POSTGRES_USER.txt
  postgres_password:
    file: secrets/POSTGRES_PASSWORD.txt
